### ISSUE TITLE
key_down is not working

### ISSUE THREAD

**Issue by oldpride** [teodesian/Selenium-Remote-Driver#480]
the latest version of Selenium::ActionChains on CPAN is 1.46

in Selenium/ActionChains.pm, at line 147, there is an obvious typo causing crash

>          sub { $self->driver->$self->driver->general_action( actions => [ { type => 'key', id => 'key', actions => [ { type => 'keyUp', value => $v } ] } ] ) };

notice the duplicate **$self->driver**. 

I removed the duplicate and tested again. key_down() is still not working perfectly.

Say if I want to type three shift+tabs. The code ideally should be

>          my $ac = Selenium::ActionChains->new(driver => $driver);
>          $ac->key_down( [ KEYS->{'shift'} ] );
>          $ac->send_keys(KEYS->{'tab'});
>          $ac->send_keys(KEYS->{'tab'});
>          $ac->send_keys(KEYS->{'tab'});
>          $ac->key_up( [ KEYS->{'shift'} ] );
>          $ac->perform;

But instead, I have to 

>          my $ac = Selenium::ActionChains->new(driver => $driver);
>          $ac->key_down( [ KEYS->{'shift'} ] );
>          $ac->send_keys(KEYS->{'tab'});
>          $ac->key_down( [ KEYS->{'shift'} ] ); # have to add this
>          $ac->send_keys(KEYS->{'tab'});
>          $ac->key_down( [ KEYS->{'shift'} ] ); # have to add this
>          $ac->send_keys(KEYS->{'tab'});
>          $ac->key_up( [ KEYS->{'shift'} ] );
>          $ac->perform;

**Comment by teodesian** [comment]
I've fixed the double invocation, and have a patch for your follow-up issue I'd like you to try:
```
diff --git a/lib/Selenium/ActionChains.pm b/lib/Selenium/ActionChains.pm
index a7b3cf3..ad01af2 100644
--- a/lib/Selenium/ActionChains.pm
+++ b/lib/Selenium/ActionChains.pm
@@ -156,14 +156,21 @@ sub send_keys {
     my $self = shift;
     my $keys = shift;
     push @{ $self->actions },
-      sub { $self->driver->get_active_element->send_keys($keys) };
+      sub {
+          $self->key_down($keys, $self->driver->get_active_element);
+          $self->key_up($keys, $self->driver->get_active_element);
+      };
     $self;
 }

 sub send_keys_to_element {
     my $self = shift;
     my ( $element, $keys ) = @_;
-    push @{ $self->actions }, sub { $element->send_keys($keys) };
+    push @{ $self->actions },
+        sub {
+            $self->key_down($keys,$element);
+            $self->key_up($keys,$element);
+        };
     $self;
 }
 ```
Let me know how that works for you, and I'll put it in the main branch.

**Comment by oldpride** [comment]
Teo, thank you for quick turnaround.

I tried your patch. I didn't work. I found multiple reasons
1. it crashed with error: Can't use string ("tab") as an ARRAY ref while "strict refs" in use at /usr/local/share/perl/5.26.1/Selenium/ActionChains.pm line 135. The reason is that $keys in send_keys() is a string but $keys in key_down() is an array
2. your patch never mentioned the modifier key (shift, alt, control). Therefore, even if you fixed above crash, logically it would still not work.

As it is challenging to keep track of which key is hold down, it may be better not to tackle it at all;  instead,  just notify users in the doc that key_down() can only apply to one following send_key(), or you can even use my workaround above as an example

**Comment by teodesian** [comment]
So you would prefer I do key_down then key_up looping over the input.  I suspected you might.

Here's a patch that probably does what you want:
```
diff --git a/lib/Selenium/ActionChains.pm b/lib/Selenium/ActionChains.pm
index a7b3cf3..8667ea7 100644
--- a/lib/Selenium/ActionChains.pm
+++ b/lib/Selenium/ActionChains.pm
@@ -153,17 +153,40 @@ sub key_up {
 }

 sub send_keys {
-    my $self = shift;
-    my $keys = shift;
+    my ($self,$keys) =@_;
+
+    # Do nothing if there are no keys to send
+    return unless $keys;
+
+    # DWIM
+    $keys = [split('',$keys)] unless ref $keys eq 'ARRAY';
+
     push @{ $self->actions },
-      sub { $self->driver->get_active_element->send_keys($keys) };
+      sub {
+          foreach my $key (@$keys) {
+              $self->key_down($key, $self->driver->get_active_element);
+              $self->key_up($key, $self->driver->get_active_element);
+          }
+      };
     $self;
 }

 sub send_keys_to_element {
-    my $self = shift;
-    my ( $element, $keys ) = @_;
-    push @{ $self->actions }, sub { $element->send_keys($keys) };
+    my ($self, $element, $keys) =@_;
+
+    # Do nothing if there are no keys to send
+    return unless $keys;
+
+    # DWIM
+    $keys = [split('',$keys)] unless ref $keys eq 'ARRAY';
+
+    push @{ $self->actions },
+        sub {
+            foreach my $key (@$keys) {
+                $self->key_down($key,$element);
+                $self->key_up($key,$element);
+            }
+        };
     $self;
 }

@@ -388,7 +411,8 @@ Releases a held mouse_button

 =head2 send_keys

-Sends keys to the currently focused element
+Sends keys to the currently focused element.
+Essentially an alias around key_down then key_up.

     Args:
         The keys to send
@@ -398,7 +422,7 @@ Sends keys to the currently focused element

 =head2 send_keys_to_element

-Sends keys to an element
+Sends keys to an element in much the same fashion as send_keys.

     Args:
         A Selenium::Remote::WebElement
```

**Comment by oldpride** [comment]
Thank you George

This time it crashed at line 135

```
Can't use string ("") as an ARRAY ref while "strict refs" in use at /usr/local/share/perl/5.26.1/Selenium/ActionChains.pm line 135.
 at /usr/local/share/perl/5.26.1/Selenium/ActionChains.pm line 135.
        Selenium::ActionChains::key_down(Selenium::ActionChains=HASH(0x5598de417c00), "\x{e004}", Selenium::Remote::WebElement=HASH(0x5598de751808)) called at /usr/local/share/perl/5.26.1/Selenium/ActionChains.pm line 167
```




key_down() in send_keys should have taken ARRAY ref, instead of string, as first arg
```
166           foreach my $key (@$keys) {
167               $self->key_down($key, $self->driver->get_active_element);
168               $self->key_up($key, $self->driver->get_active_element);

```
If I convert $key to [$key],  there is no more crash but shift+3tab still doesn't work
```
166           foreach my $key (@$keys) {
167               $self->key_down([$key], $self->driver->get_active_element);
168               $self->key_up([$key], $self->driver->get_active_element);
```

**Comment by oldpride** [comment]
I see the send_keys() logic in Perl is similar to that in Python. Therefore, the problem may be in the key_down(). Basically key_down() only affects the next typing.

For example, SHIFT + (TAB, TAB, TAB) should generate 3 backward (leftward) tabs, but Perl behavior is 1 backward tab + 2 forward tabs, ie, (SHIFT+TAB), TAB, TAB

**Comment by teodesian** [comment]
Apologies for taking a while to swing back to this.

The crash on 135 you experienced was due to not reading the documentation, key_up and key_down accept an arrayref as the first arg.  I'll DWIM it for you though, I'm sure you aren't the only one.

As to keeping down the modifier, maybe you could try:

```
$chain->key_down([$KEYS{TAB},$KEYS{SHIFT},$KEYS{SHIFT},$KEYS{SHIFT}]);
$chain->key_up([$KEYS{SHIFT},$KEYS{SHIFT},$KEYS{SHIFT},$KEYS{TAB}]);
$chain->perform();
```

**Comment by oldpride** [comment]
No worries. I'm already doing something similar to what you suggested. With the workaround,  it may be not worthwhile to improve the module anymore as it may take big effort. Thank you George
